import type { NextPage } from "next";
import Head from "next/head";
import ContainerBox from "../components/ContainerBox";
import Login from "../components/Login";
import BackgroundLayout from "../Layout/BackgroundLayout";
import LoginCenterLayout from "../Layout/LoginCenterLayout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sound Suggestion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BackgroundLayout>
          <LoginCenterLayout>
            <ContainerBox variant="minimum">
              <Login />
            </ContainerBox>
          </LoginCenterLayout>
        </BackgroundLayout>
      </main>
    </div>
  );
};

export default Home;
